-- CreateEnum
CREATE TYPE "Feature" AS ENUM ('VISITOR_MANAGEMENT', 'DELIVERY_MANAGEMENT', 'DAILY_HELP_MANAGEMENT', 'VEHICLE_MANAGEMENT', 'KIDS_CHECKOUT', 'DIRECTORY', 'OVERSTAY_ALERT', 'ATTENDANCE_MARKING', 'PRE_APPROVE_ENTRY', 'EMERGENCY_CALLING', 'HELPDESK', 'AMENITY_BOOKING', 'COMMUNICATION', 'HOME_PLANNER', 'RENT_A_PARKING', 'SOS_ALERT', 'E_INTERCOM', 'VEHICLE_SEARCH', 'NOTICE_BOARD', 'DOCUMENTS_UPLOADING', 'SURVEYS', 'ELECTION_POLLS', 'MEETING_ALIGNMENT', 'GUARD_PATROLLING', 'INVOICE_GENERATION', 'UTILITY_PAYMENT', 'RENT_PAYMENT', 'INCOME_EXPENSE_ANALYSIS', 'ASSET_INVENTORY_MANAGEMENT', 'FINANCIAL_REPORTS', 'FLATWISE_DUES', 'BUDGET_MAINTENANCE', 'RECEIPT_GENERATION', 'BANK_RECONCILIATION', 'MIS_REPORTS', 'SECURITY_DEPOSIT', 'BALANCE_SHEET_TAX');

-- AlterTable
ALTER TABLE "Community" ADD COLUMN     "planId" TEXT;

-- CreateTable
CREATE TABLE "Plan" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "features" "Feature"[],
    "price" DOUBLE PRECISION,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Plan_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SuperAdmin" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SuperAdmin_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Plan_name_key" ON "Plan"("name");

-- CreateIndex
CREATE UNIQUE INDEX "SuperAdmin_email_key" ON "SuperAdmin"("email");

-- AddForeignKey
ALTER TABLE "Community" ADD CONSTRAINT "Community_planId_fkey" FOREIGN KEY ("planId") REFERENCES "Plan"("id") ON DELETE SET NULL ON UPDATE CASCADE;
